config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about'
  get 'pages/contact'

  resources :deals
  root 'deals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :deals
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :deals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    if params[:category].blank?
      @deals = Deal.all.order("created_at DESC")

    else
      @category_id = Category.find_by(name: params[:category]).id
      @deals = Deal.where(category_id: @category_id).order("created_at DESC")
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = current_user.deals.build
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = current_user.deals.build(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    def authorized_user
      @deal = current_user.deals.find_by(id: params[:id])
      redirect_to deals_path, notice: "Not authorized to edit this deal" if @deal.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:product, :description, :deal, :cta, :brand, :category_id, :image_url, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/deals/_form.html.erb
<%= form_for(deal) do |f| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :product %>
    <%= f.text_field :product, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :deal %>
    <%= f.text_field :deal, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :URL %>
    <%= f.text_field :cta, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<br>

  <% @deals.each do |deal| %>

  <div class="col">
    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= deal.product %></h4>
          <h6 class="card-subtitle text-muted"><%= deal.deal%></h6></div>
          <img src="<%= deal.image_url %>" alt="Card image", class: "img-responsive">

        <div class="card-block">
          <p class="card-text"><%= deal.description %></p>
          <a href="<%= deal.cta %>" class="btn btn-info">Redeem offer</a>
          <%= link_to 'View more info.', deal %>
        </div>
      </div>
    </div>
  </div>

  <% end %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">

  <img src="<%= @deal.image_url %>" width="338" height="280" alt="Card image">

  <br>
  <br>

<p>
  <strong>Product:</strong>
  <%= @deal.product %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Deal:</strong>
  <%= @deal.deal %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @deal.brand %>
</p>

<a href="<%= @deal.cta %>" class="btn btn-success">Redeem offer</a>

<br>
<br>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-faded">
  <ul class="nav navbar-nav navbar-right">
    <li class="nav-item active">
      <h5><a class="nav-link" href="/">BLOGGERS DEALS</a></h5>

    </li>

  <span class="float-lg-right">

    <li class="nav-item">
      <a class="nav-link" href="/pages/about">ABOUT</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/pages/contact">CONTACT</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/"> </a>
    </li>

    <% if user_signed_in? %>

    <li>
      <!-- Signed in as <b><%= current_user.email %></b> -->
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-mini' %>
      <!-- <%= link_to "Settings", edit_user_registration_path, :class => 'btn btn-primary btn-mini' %> -->
      <% else %>
      <%= link_to new_user_session_path do %>
      <button class="btn btn-info btn-mini">Log in</button>
      <% end %>
      <% end %>
    </li>

  </span>
  </ul>
</nav>


<style>
.btn:visited {
color: #FFF
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggers Deals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">

      <ul class="nav nav-tabs">
        <li role="presentation" class="nav-item">
          <%=  link_to 'All Deals', root_path, class: "nav-link"%>
        </li>
        <% Category.all.each do |category| %>
        <li role="presentation" class="nav-item">
          <%=  link_to category.name, deals_path(category: category.name), class: "nav-link"%>
        </li>
        <% end %>
      </ul>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

<!-- css styling for links on hover. -->

<style>
  a:hover {
  background-color:transparent;
  }
</style>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>